/*
|--------------------------------------------------------------------------
| PRINCIPAL
|--------------------------------------------------------------------------
*/

// LÓGICA
// Círculo tem 360 graus...
// Um minuto tem 60 segundos...
// Um segundo possui 6 graus (360 / 60 = 6)...

import { handleClockDigital, handleRotatePointersCalc, handleRotatePointersStyle } from './';

setInterval(() => {
    let deg = 6; // Quantidade de graus que um segundo possui...
    let currentTime = new Date(); // Pega a hora atual do host...
    let hour = currentTime.getHours(); // Pega a hora...
    let minute = currentTime.getMinutes(); // Pega os minutos...
    let second = currentTime.getSeconds(); // Pega os segundos...

    handleClockDigital(hour, minute, second);
    handleRotatePointersCalc(deg, hour, minute, second);
});